### ISSUE TITLE
Command `gem server` causes `NoMethodError`

### ISSUE THREAD

**Issue by s2k** [rubygems/rubygems-server#11]
## Environment

```bash
> ruby -v && gem --version && gem info rubygems-server
ruby 3.3.6 (2024-11-05 revision 75015d4c1f) +YJIT [arm64-darwin24]
3.5.23

*** LOCAL GEMS ***

rubygems-server (0.3.0)
    Author: Hiroshi SHIBATA
    Homepage: https://github.com/rubygems/rubygems-server
    License: MIT
    Installed at: /Users/stephan/.rbenv/versions/3.3.6/lib/ruby/gems/3.3.0

    Gem::Server and allows users to serve gems for consumption by `gem
    --remote-install`.
```

Hardware:

* OS: macOS Sequoia 15.2 arm64
* Kernel: Darwin 24.2.0

## Behaviour

```bash
 > gem server
ERROR:  While executing gem ... (NoMethodError)
    undefined method `load_rdoc' for class RDoc::RubygemsHook

    Gem::RDoc.load_rdoc
             ^^^^^^^^^^
```

I expected to get a runing local gem server.
Am I doing it wrong? Should I be using something else?
Or maybe my expectation mislead?

**Comment by penangtom** [comment]
I had the same problem: I fixed it for me locally by reverting `rdoc` to 6.8.1 (from 6.9.0)

Apparently the `Gem::RDoc.load_rdoc` invocation in `rubygems-server (0.3.0)` works with `rdoc <6.9.0` but not subsequently.
